### PR TITLE
Update configuration.md

### PR DESCRIPTION
**Pull request by bungbloopity**
Added documentation for the `clear-text` reporter in `configuration.md`

### CODE REVIEW

**Comment by bungbloopity** [comment]
This is my first open-source contribution! It's not any actual code but I wanted to help in any way I could. Let me know if anything can be done better. Thank you!

**Review by nicojs — CHANGES_REQUESTED** [review]
Thanks a lot for picking this up!

The console settings are actually not implemented as command line arguments. See https://github.com/stryker-mutator/stryker-js/blob/master/packages/core/src/stryker-cli.ts#L48

Could you remove them from these docs? Thanks!

**Comment by bungbloopity** [comment]
Got it, second commit should be correct

**Review by nicojs — APPROVED** [review]
🚀

**Pull request merged**
