### PR TITLE
feat(init): add svelte custom initializer

### PR DESCRIPTION
**Pull request by nicojs**
Add the choice for "svelte" in `stryker init`.

```
nicojs@NicoJ01 ~/github/svelte-project $ npx stryker init
? Are you using one of these frameworks? Then select a preset configuration. svelte
? Which test runner are you using? jest
? Are you using native EcmaScript modules? (see https://jestjs.io/docs/ecmascript-modules) Yes
? What file type do you want for your config file? JSON
Writing & formatting stryker.config.json...
? Which package manager do you want to use? npm
Installing NPM dependencies...
npm i --save-dev @stryker-mutator/jest-runner
```

Also document svelte in a guide doc.

### CODE REVIEW

**Comment by nicojs** [comment]
@TeunLamers what do you think? I'm trying to get this released tomorrow.

**Comment by TeunLamers** [comment]
Sorry, I’ve only just seen this now. I had a training. No comments

**Comment by nicojs** [comment]
No problemo, we can always add changes later :)

**Comment by nicojs** [comment]
We do need a blog article for the major version, announcing Svelte support. Want to help there?

**Comment by TeunLamers** [comment]
Yes, for sure!

**Pull request merged**
