### PR TITLE
feat(instrumenter): add expression mutator for Date (#4917)

### PR DESCRIPTION
**Pull request by boretti**
It would be interesting to have mutation produced for operation on Date.

Expression like :

```typescript
aDate.setDate(aDate.getDate()+1)
```
will produce interesting mutation based on the +1. It would also be interesting to have mutation changing the `setDate` or `getDate` operation (as updating month and not the day of month).

I propose to add the following mutation (to `method-expression-mutator`) :

* `getDate` to/from `getMonth`
* `setDate` to/from `setMonth`
* `getHours` to/from `getMinutes`
* `setHours` to/from `setMinutes`

See issue #4917

### CODE REVIEW

**Comment by boretti** [comment]
Update based on proposal in the issue.

**Review by nicojs — COMMENTED** [review]
The code looks great, But I first want to resolve the discussion in #4917 before merging

**Comment by boretti** [comment]
Updated according exchange in the issue

**Review by nicojs — APPROVED** [review]

**Comment by nicojs** [comment]
Thanks! ❤️

**Pull request merged**
