### PR TITLE
chore: use "files" instead of .npmignore

### PR DESCRIPTION
**Pull request by regseb**
Use property `files` instead of `.npmignore` file to publish only the files you need, lighten packages, and reduce the risk of publishing a useless file.

> **[_Publishing what you mean to publish_](https://blog.npmjs.org/post/165769683050/publishing-what-you-mean-to-publish):** There’s an even better way of controlling exactly which files are published with your package: [whitelisting with the files array](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#files).

List of files that will **no longer** be published with this PR:

- `api`, package reduced from 62.4ko to 34.2ko (54.8%)
  - `src-generated/`
  - `src/`
  - `.mocharc.cjs`, the file has been renamed from `.mocharc.jsonc` to `.mocharc.cjs`, but the name hasn't been changed in the `.npmignore`. https://github.com/stryker-mutator/stryker-js/commit/051ec937809468751a74c9e01cacd27ceb1acca2
  - `CHANGELOG.md`, this file is no longer included by default since npm [v7.12.0](https://docs.npmjs.com/cli/v7/using-npm/changelog#v7120-2021-05-06): _Do not force include history, changelogs, notice_
- `core`
  - `src/`
  - `.mocharc.cjs`
  - `CHANGELOG.md`
- `cucumber-runner`
  - `src-generated/`
  - `src/`
  - `.editorconfig`
  - `.eslintignore`
  - `.mocharc.cjs`
  - `prettierrc`
  - `CHANGELOG.md`
- `grunt-stryker`
  - `CHANGELOG.md`
- `instrumenter`
  - `src/`
  - `.mocharc.cjs`
  - `CHANGELOG.md`
- `jasmine-runner`
  - `src-generated/`
  - `src/`
  - `.mocharc.cjs`
  - `CHANGELOG.md`
- `jest-runner`
  - `src-generated/`
  - `src/`
  - `.mocharc.cjs`
  - `CHANGELOG.md`
- `karma-runner`
  - `src-generated/`
  - `src/`
  - `.mocharc.cjs`
  - `CHANGELOG.md`
- `mocha-runner`
  - `src-generated/`
  - `src/`
  - `.mocharc.cjs`
  - `CHANGELOG.md`
- `tap-runner`
  - `src-generated/`
  - `src/`
  - `.mocharc.cjs`
  - `CHANGELOG.md`
- `typescript-checker`
  - `src-generated/`
  - `src/`
  - `.mocharc.cjs`
  - `CHANGELOG.md`
- `util`
  - `src/`
  - `.mocharc.cjs`
  - `CHANGELOG.md`
- `vitest-runner`
  - `src-generated/`
  - `src/`
  - `.mocharc.cjs`
  - `CHANGELOG.md`

### CODE REVIEW

**Review by nicojs — CHANGES_REQUESTED** [review]
Hi @regseb thanks for participating here. 

I agree with all files, except maybe `src` and `src-generated`. I started including them when vscode started logging warnings for missing sources of sourcemaps (also in `node_modules`). I'm pretty sure an issue was also raised, but I can't seem to find it. 

What's your opinion on it?

**Comment by regseb** [comment]
I've added the `src/` and `src-generated/` directories.

It's a first step to replace `.npmignore` by `"files"`. The next step will be to see about source maps, but I don't know how that works.

**Review by nicojs — APPROVED** [review]

**Comment by nicojs** [comment]
Thanks!

**Comment by ericcornelissen** [comment]
I noticed in [the diff of v7.1.1 -> 7.2.0](https://diff.ecosyste.ms/diff?url_1=https%3A%2F%2Fregistry.npmjs.org%2F%40stryker-mutator%2Fcore%2F-%2Fcore-7.1.1.tgz&url_2=https%3A%2F%2Fregistry.npmjs.org%2F%40stryker-mutator%2Fcore%2F-%2Fcore-7.2.0.tgz), which included this change, that there's actually a bunch of files newly included that don't need to be (even though the release line reads "ignore unused files"). Most notably test(/spec) files.

Primarily I wanted to raise the above. But I also wanted to share my perspective on this matter. Personally, I tend to favor a whitelisted-style `.npmignore` file ([example](https://github.com/ericcornelissen/shescape/blob/c7c41e94d929cbdc3c22055319cdb30bd9631397/.npmignore)) over the "files" array because it makes managing complex sub-folder rules a bit easier to manage (also for [source maps](https://github.com/stryker-mutator/stryker-js/pull/4405#issuecomment-1732538897)) while providing the same benefits mentioned/referenced here.

**Comment by regseb** [comment]
@ericcornelissen Thanks for the feedback. There's a problem in my pull request. The `"dist/"` directories contain test files and _tsbuildinfo_. I'll make a new pull request to correct these problems.

---

For [`.npmignore`](https://docs.npmjs.com/cli/v10/using-npm/developers#keeping-files-out-of-your-package) / [`"files"`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#files), I prefer `"files"` because :

- the list of files to be published is in the same file as the `"exports"`, `"main"`, `"bin"` and `"types"` properties.
- it's a _positive_ list, whereas `.npmignore` is a _negative_ list ([_Avoid negative conditionals_](https://github.com/ryanmcdermott/clean-code-javascript#avoid-negative-conditionals)).

All `.npmignore` features can be used in `"files"`:

> File patterns follow a similar syntax to `.gitignore`, but reversed: including a file, directory, or glob pattern (`*`, `**/*`, and such) will make it so that file is included in the tarball when it's packed.

Here's the equivalent of your example with `"files"`:

```JSON
{
  "files": [
    "docs/",
    "src/",
    "CHANGELOG.md",
    "index.cjs",
    "index.d.cts",
    "index.d.ts",
    "index.js",
    "package.json",
    "LICENSE",
    "README.md",
    "SECURITY.md",
    "testing.cjs",
    "testing.d.cts",
    "testing.d.ts",
    "testing.js"
  ]
}
```

**Comment by ericcornelissen** [comment]
Good to know the `"files"` array supports the same expressions as `.npmignore` - in that case it's a matter of taste/preference :+1:

**Pull request merged**
