### PR TITLE
Add "% score of covered" column to the clear text report

### PR DESCRIPTION
**Pull request by kirankashyap**
The metric `mutationScoreBasedOnCoveredCode` is already calculated by Stryker and is present in the metrics object.

This PR shows this additional metric in the clear text report.

Continuing the trend from https://github.com/stryker-mutator/mutation-testing-elements/pull/3310

Thanks to @vivganes for motivation

### CODE REVIEW

**Comment by nicojs** [comment]
Thanks for opening this PR. The % based on covered would be a great metric to add to the clear-text reporter. However, horizontal real estate in the console is even more scarce than in the browser. 

I've run the clear-text table for the `util` package. This what I get.

```
------------------------------|---------|--------------------|----------|-----------|------------|----------|----------|
File                          | % score | % score of covered | # killed | # timeout | # survived | # no cov | # errors |
------------------------------|---------|--------------------|----------|-----------|------------|----------|----------|
All files                     |   85.47 |              89.29 |       96 |         4 |         12 |        5 |       82 |
 child-process-as-promised.ts |     n/a |                n/a |        0 |         0 |          0 |        0 |        0 |
 deep-merge.ts                |   71.43 |              71.43 |       15 |         0 |          6 |        0 |        2 |
 errors.ts                    |   93.75 |              93.75 |       15 |         0 |          1 |        0 |       10 |
 find-unserializables.ts      |   91.67 |              91.67 |       22 |         0 |          2 |        0 |       30 |
 immutable.ts                 |  100.00 |             100.00 |        8 |         0 |          0 |        0 |       14 |
 noop-logger.ts               |  100.00 |             100.00 |        6 |         0 |          0 |        0 |        6 |
 not-empty.ts                 |  100.00 |             100.00 |        7 |         0 |          0 |        0 |        1 |
 platform.ts                  |    0.00 |               0.00 |        0 |         0 |          0 |        3 |        2 |
 require-resolve.ts           |    0.00 |               0.00 |        0 |         0 |          0 |        2 |        2 |
 split.ts                     |   83.33 |              83.33 |        5 |         0 |          1 |        0 |        4 |
 string-utils.ts              |   90.91 |              90.91 |       10 |         0 |          1 |        0 |        7 |
 stryker-error.ts             |  100.00 |             100.00 |        3 |         0 |          0 |        0 |        0 |
 task.ts                      |   90.00 |              90.00 |        5 |         4 |          1 |        0 |        4 |
------------------------------|---------|--------------------|----------|-----------|------------|----------|----------|
```

We could shave off an entire column's worth of width by implementing the same proposal as in mutation-testing-elements:

```
------------------------------|------------------|----------|-----------|------------|----------|----------|
                              | % Mutation score |          |           |            |          |          |
File                          | total    covered | # killed | # timeout | # survived | # no cov | # errors |
------------------------------|--------|---------|----------|-----------|------------|----------|----------|
All files                     |  85.47 |   89.29 |       96 |         4 |         12 |        5 |       82 |
 child-process-as-promised.ts |    n/a |     n/a |        0 |         0 |          0 |        0 |        0 |
 deep-merge.ts                |  71.43 |   71.43 |       15 |         0 |          6 |        0 |        2 |
 errors.ts                    |  93.75 |   93.75 |       15 |         0 |          1 |        0 |       10 |
 find-unserializables.ts      |  91.67 |   91.67 |       22 |         0 |          2 |        0 |       30 |
 immutable.ts                 | 100.00 |  100.00 |        8 |         0 |          0 |        0 |       14 |
 noop-logger.ts               | 100.00 |  100.00 |        6 |         0 |          0 |        0 |        6 |
 not-empty.ts                 | 100.00 |  100.00 |        7 |         0 |          0 |        0 |        1 |
 platform.ts                  |   0.00 |    0.00 |        0 |         0 |          0 |        3 |        2 |
 require-resolve.ts           |   0.00 |    0.00 |        0 |         0 |          0 |        2 |        2 |
 split.ts                     |  83.33 |   83.33 |        5 |         0 |          1 |        0 |        4 |
 string-utils.ts              |  90.91 |   90.91 |       10 |         0 |          1 |        0 |        7 |
 stryker-error.ts             | 100.00 |  100.00 |        3 |         0 |          0 |        0 |        0 |
 task.ts                      |  90.00 |   90.00 |        5 |         4 |          1 |        0 |        4 |
------------------------------|--------|---------|----------|-----------|------------|----------|----------|
```

What do you think?

Also, some unit tests and e2e tests are failing.

**Comment by kirankashyap** [comment]
Thanks for your feedback @nicojs 

I will make the changes.

**Comment by kirankashyap** [comment]
hi @nicojs, I have made the changes you suggested. Please let me know me know your feedback.

**Comment by kirankashyap** [comment]
hey @nicojs, following up on this. Can you please start the workflow for build? Please let me know if you have any feedback as well. Here is how the output looks

```
----------|------------------|----------|-----------|------------|----------|----------|
          | % Mutation score |          |           |            |          |          |
File      | total  | covered | # killed | # timeout | # survived | # no cov | # errors |
----------|--------|---------|----------|-----------|------------|----------|----------|
All files |  50.01 |    0.00 |        0 |         0 |          0 |        0 |        0 |
          |  50.00 |    0.00 |        0 |         0 |          0 |        0 |        0 |
          |  49.99 |    0.00 |        0 |         0 |          0 |        0 |        0 |
----------|--------|---------|----------|-----------|------------|----------|----------|
```

**Comment by nicojs** [comment]
Thank you! I will try to review it this week

**Review by nicojs — CHANGES_REQUESTED** [review]
I don't think the approach you chose works. I've run `npm run stryker -- --reporters clear-text` in the `util` package and this is the result:

```
------------------------------|---------------------------------------|----------|-----------|------------|----------|----------|
                              |                      % Mutation score |          |           |            |          |          |
File                          | total  | covered | # killed | # timeout | # survived | # no cov | # errors |
------------------------------|--------|---------|----------|-----------|------------|----------|----------|
All files                     |  85.47 |   89.29 |       96 |         4 |         12 |        5 |       82 |
 child-process-as-promised.ts |    n/a |     n/a |        0 |         0 |          0 |        0 |        0 |
 deep-merge.ts                |  71.43 |   71.43 |       15 |         0 |          6 |        0 |        2 |
 errors.ts                    |  93.75 |   93.75 |       15 |         0 |          1 |        0 |       10 |
 find-unserializables.ts      |  91.67 |   91.67 |       22 |         0 |          2 |        0 |       30 |
 immutable.ts                 | 100.00 |  100.00 |        8 |         0 |          0 |        0 |       14 |
 noop-logger.ts               | 100.00 |  100.00 |        6 |         0 |          0 |        0 |        6 |
 not-empty.ts                 | 100.00 |  100.00 |        7 |         0 |          0 |        0 |        1 |
 platform.ts                  |   0.00 |    0.00 |        0 |         0 |          0 |        3 |        2 |
 require-resolve.ts           |   0.00 |    0.00 |        0 |         0 |          0 |        2 |        2 |
 split.ts                     |  83.33 |   83.33 |        5 |         0 |          1 |        0 |        4 |
 string-utils.ts              |  90.91 |   90.91 |       10 |         0 |          1 |        0 |        7 |
 stryker-error.ts             | 100.00 |  100.00 |        3 |         0 |          0 |        0 |        0 |
 task.ts                      |  90.00 |   90.00 |        5 |         4 |          1 |        0 |        4 |
------------------------------|--------|---------|----------|-----------|------------|----------|----------
```

Instead of using the `firstRowColumns`, I think it's better to add a `group` to the `Column` class. By default it's `undefined`, but if you fill it with a string (`'% Mutation score'`) it is used to group the subsequent columns. That way, you can also use the `width` of the underlying columns to determine the width of the group.

**Comment by kirankashyap** [comment]
hi @nicojs , thanks for your inputs. I have made the changes. Now the output of `npm run stryker -- --reporters clear-text` in the `util` package looks like this. 

```
------------------------------|--------|---------|----------|-----------|------------|----------|----------|
                              | % Mutation score |          |           |            |          |          |
File                          |  total | covered | # killed | # timeout | # survived | # no cov | # errors |
------------------------------|--------|---------|----------|-----------|------------|----------|----------|
All files                     |  85.47 |   89.29 |       96 |         4 |         12 |        5 |       82 |
 child-process-as-promised.ts |    n/a |     n/a |        0 |         0 |          0 |        0 |        0 |
 deep-merge.ts                |  71.43 |   71.43 |       15 |         0 |          6 |        0 |        2 |
 errors.ts                    |  93.75 |   93.75 |       15 |         0 |          1 |        0 |       10 |
 find-unserializables.ts      |  91.67 |   91.67 |       22 |         0 |          2 |        0 |       30 |
 immutable.ts                 | 100.00 |  100.00 |        8 |         0 |          0 |        0 |       14 |
 noop-logger.ts               | 100.00 |  100.00 |        6 |         0 |          0 |        0 |        6 |
 not-empty.ts                 | 100.00 |  100.00 |        7 |         0 |          0 |        0 |        1 |
 platform.ts                  |   0.00 |    0.00 |        0 |         0 |          0 |        3 |        2 |
 require-resolve.ts           |   0.00 |    0.00 |        0 |         0 |          0 |        2 |        2 |
 split.ts                     |  83.33 |   83.33 |        5 |         0 |          1 |        0 |        4 |
 string-utils.ts              |  90.91 |   90.91 |       10 |         0 |          1 |        0 |        7 |
 stryker-error.ts             | 100.00 |  100.00 |        3 |         0 |          0 |        0 |        0 |
 task.ts                      |  90.00 |   90.00 |        5 |         4 |          1 |        0 |        4 |
------------------------------|--------|---------|----------|-----------|------------|----------|----------|
```

Please have a look. Please let me know if anything needs to change.

**Comment by nicojs** [comment]
@kirankashyap I've refactored it a bit. 

I started with fixing 2 things: 

1. The column split (`|`) atop "% Mutation score"
2. Sometimes, a space was missing in front of "% Mutation score". This happened when there was no "100.00" in the column. That reduced the column width, resulting in the missing padding.

I've changed the grouping by introducing an abstract `Column` class, which contains the shared parts between a column group and a single column. The `SingleColumn` and `GroupColumn` inherit from it and implement the necessary code to make it work.

What do you think?

**Comment by nicojs** [comment]
Note: the e2e test still needs updating. Can you take care of that? Or do you want me to help?

**Comment by kirankashyap** [comment]
Hi @nicojs, thanks for your feedback. I'll update e2e test.

**Comment by kirankashyap** [comment]
Hi @nicojs , I made changes to one e2e test. But I was not able to get the result (my computer doesn't have great specs tbh). Is it ok if you can please CI job once more so that I can see the results here?

**Comment by vivganes** [comment]
I tried running the e2e test in my local computer.  I too am receiving different errors everytime.
@kirankashyap I guessyou need to wait until the github actions are run again to see if your tests pass.

**Comment by kirankashyap** [comment]
Hi @nicojs, All the tests are passing. Can you please merge the changes?

**Pull request merged**
